Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1600
      Handler: cke_migration.App
      CodeUri: /Users/temporaryadmin/IdeaProjects/S3Lambda/CKE
      Runtime: java11
      Architectures:
        - x86_64